---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: clickhouse
  tasks:
    - name: "Create a directory if it does not exist"
      ansible.builtin.file:
        path: /opt/vector
        state: directory
        mode: '0777'
    - name: "Unarchive a vector that needs to be downloaded"
      ansible.builtin.unarchive:
        src: https://packages.timber.io/vector/0.22.2/vector-0.22.2-x86_64-unknown-linux-musl.tar.gz
        dest: /opt/vector
        remote_src: yes
      tags: skip_ansible_lint
    - name: "Copy file"
      ansible.builtin.template:
        src: /home/khordv/repo-github/08-ansible/files/consul/vector.toml.j2
        dest: /opt/vector/config/vector.toml
        mode: '0755'
    - name: "Create a directory"
      ansible.builtin.file:
        path: /var/lib/vector
        state: directory
        mode: '0755'
    - name: "Run vector"
      ansible.builtin.command: "vector --config /opt/vector/config/vector.toml:"
      args:
        chdir: /opt/vector/bin
      tags: skip_ansible_lint
